cmake_minimum_required(VERSION 3.8)
project(semantic_costmap_layer_msgs)

# find dependencies
find_package(ament_cmake REQUIRED)
find_package(rosidl_default_generators REQUIRED)
find_package(std_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)

rosidl_generate_interfaces(${PROJECT_NAME}
  "msg/SemanticObject.msg"
  "msg/SemanticObjectArray.msg"
  DEPENDENCIES std_msgs geometry_msgs
)

ament_export_dependencies(
  rosidl_default_runtime
)

ament_package()
